version: '3.6'
services:

  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb-database
    restart: always
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_USER=darias
      - INFLUXDB_ADMIN_PASSWORD=research
    networks:
      - internal
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb

  telegraf:
    image: telegraf
    container_name: telegraf-service
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    networks:
      - internal
    ports:
    - '8125:8125'

  pushgateway:
#    image: prom/pushgateway:v1.0.0
    image: prom/pushgateway:latest
    container_name: pushgateway-service
    depends_on:
      - telegraf
    networks:
      - internal
    ports:
     - 9091:9091

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-server
    depends_on:
      - pushgateway
    ports:
      - 9090:9090
    networks:
      - internal
    volumes:
      - prometheus_volume:/prometheus/
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: always
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=darias
      - GF_SECURITY_ADMIN_PASSWORD=research
      - GF_INSTALL_PLUGINS=aidanmountford-html-panel
    links:
      - influxdb
    networks:
      - internal
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/provisioning/custom.ini:/etc/grafana/grafana.ini
      
volumes:
  grafana_data: {}
  influxdb_data: {}
  prometheus_volume:
    external: false

networks:
  internal: